/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chucnang;
import static Chucnang.TNXE.convertUtilDateToSqlDate;
import MenuConnect.Connect;
    import java.awt.Dimension;
    import java.awt.Graphics;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
    import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class LAPPHIEUSC extends javax.swing.JFrame {
    DefaultTableModel Y = new DefaultTableModel();

    /**
     * Creates new form LAPPHIEUSC
     */
    public LAPPHIEUSC() {
        initComponents();
        Load();
        LoadCB();
        LoadCB1();
    }
public void Load(){
        try{
            Connect C = new Connect();
            Connection conn = C.getConnection();
            int number;
            Vector row, column = null;
            column = new Vector();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from CHITIETSUACHUA");
            ResultSetMetaData metadata = rs.getMetaData();
            number = metadata.getColumnCount();
            for (int i = 1; i <= number;  i++){
                column.add(metadata.getColumnName(i));   
            }
            Y.setColumnIdentifiers(column);
            while(rs.next()){
                row = new Vector();
                for(int i=1;i<=number; i++){
                    row.addElement(rs.getString(i));
                }
                Y.addRow(row);
                jTableptsc.setModel(Y);
            }
        }catch(Exception ex) {
            System.out.println(ex.toString());
        }
    jTableptsc.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(jTableptsc.getSelectedRow()>=0){                    
                    jComboBoxmpsc.setSelectedItem(jTableptsc.getValueAt(jTableptsc.getSelectedRow(),0)+ "");
                    jComboBoxtenpt.setSelectedItem(jTableptsc.getValueAt(jTableptsc.getSelectedRow(),1)+ "");
                    jTextFieldsl.setText(jTableptsc.getValueAt(jTableptsc.getSelectedRow(),2) + "");
                    jTextFieldnd.setText(jTableptsc.getValueAt(jTableptsc.getSelectedRow(),3) + "");
                }
            }
        });
    }
    public void LoadCB(){
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement ps = conn.prepareStatement("select MASC from PHIEUSUACHUA");
            ResultSet rs =ps.executeQuery();
            while(rs.next()){
                jComboBoxmpsc.addItem(rs.getString("MASC"));
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }
    public void LoadCB1(){
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement ps =  conn.prepareStatement("select MAPT from PHUTUNG");
            ResultSet rs =ps.executeQuery();
            while(rs.next()){
                jComboBoxtenpt.addItem(rs.getString("MAPT"));
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxmpsc = new javax.swing.JComboBox<String>();
        jComboBoxtenpt = new javax.swing.JComboBox<String>();
        jTextFieldsl = new javax.swing.JTextField();
        jTextFieldnd = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelbsx = new javax.swing.JLabel();
        jLabeltpt = new javax.swing.JLabel();
        jLabelttt = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButtonlaphd = new javax.swing.JButton();
        jButtonthoat = new javax.swing.JButton();
        jButtonxoa = new javax.swing.JButton();
        jButtonthem = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableptsc = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();

        setTitle("PHIẾU SỬA CHỬA");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 61, 78));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHỨC NĂNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 406, -1, -1));

        jPanel4.setBackground(new java.awt.Color(61, 79, 105));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxmpsc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxmpsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxmpscMouseClicked(evt);
            }
        });
        jComboBoxmpsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxmpscActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxmpsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 150, 40));

        jComboBoxtenpt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxtenpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtenptActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxtenpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, 40));

        jTextFieldsl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel4.add(jTextFieldsl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 300, 40));

        jTextFieldnd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel4.add(jTextFieldnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 300, 40));

        jPanel2.setBackground(new java.awt.Color(54, 71, 93));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Barcode_Scanner_48px.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã Phiếu Sửa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 40));

        jPanel5.setBackground(new java.awt.Color(54, 71, 93));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Gas_Pump_40px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên Phụ Tùng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, -1));

        jPanel6.setBackground(new java.awt.Color(54, 71, 93));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Numbers_40px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Số Lượng");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jPanel7.setBackground(new java.awt.Color(54, 71, 93));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Create_Document_40px.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(54, 71, 93));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nội Dung");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, -1));

        jPanel11.setBackground(new java.awt.Color(54, 71, 93));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("THÔNG TIN");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(210, 210, 210))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 40));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Trạng thái:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabelbsx.setFont(new java.awt.Font("Thuduc", 1, 24)); // NOI18N
        jLabelbsx.setForeground(new java.awt.Color(255, 255, 255));
        jLabelbsx.setText(" ");
        jPanel4.add(jLabelbsx, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 140, 40));

        jLabeltpt.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabeltpt.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltpt.setText(" ");
        jPanel4.add(jLabeltpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 150, 40));

        jLabelttt.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabelttt.setForeground(new java.awt.Color(255, 0, 0));
        jLabelttt.setText(" ");
        jPanel4.add(jLabelttt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 110, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 560, 360));

        jPanel8.setBackground(new java.awt.Color(61, 79, 105));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonlaphd.setBackground(new java.awt.Color(204, 204, 255));
        jButtonlaphd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonlaphd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Application.png"))); // NOI18N
        jButtonlaphd.setText("LẬP PS");
        jButtonlaphd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlaphdActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonlaphd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 112, 60));

        jButtonthoat.setBackground(new java.awt.Color(204, 204, 255));
        jButtonthoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Exit.png"))); // NOI18N
        jButtonthoat.setText("THOÁT");
        jButtonthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthoatActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonthoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 107, 60));

        jButtonxoa.setBackground(new java.awt.Color(204, 204, 255));
        jButtonxoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Delete.png"))); // NOI18N
        jButtonxoa.setText("XÓA");
        jButtonxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoaActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 107, 60));

        jButtonthem.setBackground(new java.awt.Color(204, 204, 255));
        jButtonthem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Apply.png"))); // NOI18N
        jButtonthem.setText("THÊM");
        jButtonthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 113, 60));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 560, 140));

        jPanel9.setBackground(new java.awt.Color(61, 79, 105));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableptsc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableptsc.setRowHeight(22);
        jTableptsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableptscMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableptsc);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 530, 480));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 550, 520));

        jPanel10.setBackground(new java.awt.Color(29, 187, 156));

        jLabel6.setBackground(new java.awt.Color(29, 187, 156));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BẢNG PHỤ TÙNG SỬA CHỬA");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(354, 354, 354))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 50));

        jPanel12.setBackground(new java.awt.Color(29, 187, 156));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 1190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthoatActionPerformed
        // TODO add your handling code here: THOÁT KHỎI  PHIẾU LẬP PHIẾU SỬA CHỬA
        if(JOptionPane.showConfirmDialog(this,"Xác Nhận Thoát?","Đồng Ý",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){ 
        this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonthoatActionPerformed

    private void jButtonthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemActionPerformed
        // TODO add your handling code here: thêm chi tiết sửa chửa
        try{
        Connect C = new Connect();
        Connection conn = C.getConnection();
        PreparedStatement ps = conn.prepareStatement("insert into dbo.CHITIETSUACHUA values(?,?,?,?)");
        ps.setString(1, jComboBoxmpsc.getSelectedItem().toString());
        ps.setString(2, jComboBoxtenpt.getSelectedItem().toString());
        ps.setString(3, jTextFieldsl.getText());
        ps.setString(4, jTextFieldnd.getText());
        int chk = ps.executeUpdate();
        if (chk  >0){
        //    JOptionPane.showMessageDialog(this, "Đã thêm thành công !");
            jLabelttt.setText("Thêm thành công");
        }        
            Y.setRowCount(0);
            Load();
    }catch(Exception ex){
        ex.getMessage();
        System.out.println(ex.toString());
        JOptionPane.showMessageDialog(this, "Thêm thất bại ! Hãy nhập kỹ lại thông tin");
        jLabelttt.setText("Thêm thất bại");
    }
    jTextFieldsl.setText("");
    jTextFieldnd.setText("");
    }//GEN-LAST:event_jButtonthemActionPerformed

    private void jButtonxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoaActionPerformed
        // TODO add your handling code here: xóa cthd
        try {
            Connect c = new Connect();
            Connection conn = c.getConnection();
            PreparedStatement ps = conn.prepareStatement("delete dbo.CHITIETSUACHUA where MASC=?");
            ps.setString(1,jTableptsc.getValueAt(jTableptsc.getSelectedRow(),0).toString());
            if(JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa không?","Ðồng Ý",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                jLabelttt.setText("Xóa thành công");
                ps.executeUpdate();
                Y.setRowCount(0);
                Load();
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
            jLabelttt.setText("Xóa thất bại");
            JOptionPane.showMessageDialog(this, "Xóa thất bại !");
        }
        jTextFieldsl.setText("");
        jTextFieldnd.setText("");
    }//GEN-LAST:event_jButtonxoaActionPerformed

    private void jButtonlaphdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlaphdActionPerformed
        // TODO add your handling code here:lập  phiếu suất
        if(JOptionPane.showConfirmDialog(this,"Bạn có muốn lập hóa đơn không?","Đồng Ý",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        { 
        this.setVisible(false);
        LAPHOADON n = new LAPHOADON();
        n.setVisible(true);
        }
    }//GEN-LAST:event_jButtonlaphdActionPerformed

    private void jComboBoxmpscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxmpscActionPerformed
        // TODO add your handling code here: hiện tên bsx
    try{
        Connect c = new Connect();
        Connection conn = c.getConnection();
        PreparedStatement p = conn.prepareStatement("select * from PHIEUSUACHUA");
        ResultSet rs = p.executeQuery();
        while(rs.next())
        {
            if(jComboBoxmpsc.getSelectedItem().toString().equalsIgnoreCase(rs.getString("MASC"))){    
                jLabelbsx.setText(rs.getString("BSX"));
            }
        }
            }catch (SQLException ex){
                Logger.getLogger(LAPHOADON.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jComboBoxmpscActionPerformed

    private void jComboBoxtenptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtenptActionPerformed
        // TODO add your handling code here: hiện tên phụ tùng
        jLabelttt.setText("");
    try{
        Connect c = new Connect();
        Connection conn = c.getConnection();
        PreparedStatement p = conn.prepareStatement("select * from PHUTUNG");
        ResultSet rs = p.executeQuery();
        while(rs.next())
        {
            if(jComboBoxtenpt.getSelectedItem().toString().equalsIgnoreCase(rs.getString("MAPT"))){    
                jLabeltpt.setText(rs.getString("TENPT"));
            }
        }
            }catch (SQLException ex){
                Logger.getLogger(LAPHOADON.class.getName()).log(Level.SEVERE, null, ex);
            }   
    }//GEN-LAST:event_jComboBoxtenptActionPerformed

    private void jComboBoxmpscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxmpscMouseClicked
        // TODO add your handling code here:
        jLabelttt.setText("");
    }//GEN-LAST:event_jComboBoxmpscMouseClicked

    private void jTableptscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableptscMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableptscMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAPPHIEUSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAPPHIEUSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAPPHIEUSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAPPHIEUSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAPPHIEUSC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonlaphd;
    private javax.swing.JButton jButtonthem;
    private javax.swing.JButton jButtonthoat;
    private javax.swing.JButton jButtonxoa;
    private javax.swing.JComboBox<String> jComboBoxmpsc;
    private javax.swing.JComboBox<String> jComboBoxtenpt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelbsx;
    private javax.swing.JLabel jLabeltpt;
    private javax.swing.JLabel jLabelttt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableptsc;
    private javax.swing.JTextField jTextFieldnd;
    private javax.swing.JTextField jTextFieldsl;
    // End of variables declaration//GEN-END:variables
}
