/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chucnang;
import MenuConnect.Connect;
import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class THEMPT extends javax.swing.JFrame {
    DefaultTableModel Y = new DefaultTableModel();

    /**
     * Creates new form THEMPT
     */
    public THEMPT() {
        initComponents();
        Load();
        LoadCB();
    }
public void Load(){
        try{
            Connect C = new Connect();
            Connection conn = C.getConnection();
            int number;
            Vector row, column = null;
            column = new Vector();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from PHUTUNG");
            ResultSetMetaData metadata = rs.getMetaData();
            number = metadata.getColumnCount();
            for (int i = 1; i <= number;  i++){
                column.add(metadata.getColumnName(i));   
            }
            Y.setColumnIdentifiers(column);
            while(rs.next()){
                row = new Vector();
                for(int i=1;i<=number; i++){
                    row.addElement(rs.getString(i));
                }
                Y.addRow(row);
                jTablept.setModel(Y);
            }
        }catch(Exception ex) {
            System.out.println(ex.toString());
        }
    jTablept.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(jTablept.getSelectedRow()>=0){
                    //ten truong
                    jTextFieldtenpt.setText(jTablept.getValueAt(jTablept.getSelectedRow(),1) + "");
                    jTextFieldslpt.setText(jTablept.getValueAt(jTablept.getSelectedRow(),2) + "");
                    jTextFielddongia.setText(jTablept.getValueAt(jTablept.getSelectedRow(),3) + "");                    
                    jComboBoxloaitc.setSelectedItem(jTablept.getValueAt(jTablept.getSelectedRow(),4)+ "");
                }
            }
        });
    }
    public void LoadCB(){
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement ps = conn.prepareStatement("select MATC from TIENCONG");
            ResultSet rs =ps.executeQuery();
            while(rs.next()){
                jComboBoxloaitc.addItem(rs.getString("MATC"));
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldtenpt = new javax.swing.JTextField();
        jTextFieldslpt = new javax.swing.JTextField();
        jTextFielddongia = new javax.swing.JTextField();
        jComboBoxloaitc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabeltt = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabeltentc = new javax.swing.JLabel();
        jLabeltc = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablept = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButtonthoat = new javax.swing.JButton();
        jButtonxoa = new javax.swing.JButton();
        jButtonsua = new javax.swing.JButton();
        jButtonthem = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setTitle("THÊM PHỤ TÙNG XE");

        jPanel1.setBackground(new java.awt.Color(45, 61, 78));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 71, 93));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên Phụ Tùng");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 29));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Đơn Giá");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Loại Tiền Công");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 50));

        jTextFieldtenpt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldtenpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldtenptMouseClicked(evt);
            }
        });
        jTextFieldtenpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtenptActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldtenpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 320, 50));

        jTextFieldslpt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldslpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 320, 50));

        jTextFielddongia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jTextFielddongia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 320, 50));

        jComboBoxloaitc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxloaitc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxloaitcActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxloaitc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 190, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Gas_Pump_40px.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Natural_User_Interface_2_40px.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 50));

        jPanel6.setBackground(new java.awt.Color(61, 79, 105));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));

        jPanel8.setBackground(new java.awt.Color(61, 79, 105));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Số Lượng");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Numbers_40px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 50));

        jPanel12.setBackground(new java.awt.Color(61, 79, 105));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_US_Dollar_40px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jPanel13.setBackground(new java.awt.Color(61, 79, 105));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jPanel11.setBackground(new java.awt.Color(61, 79, 105));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" THÔNG TIN PHỤ TÙNG XE");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 50));

        jLabeltt.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabeltt.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabeltt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 130, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Thông báo:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, 20));

        jLabeltentc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabeltentc.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltentc.setText(" ");
        jPanel2.add(jLabeltentc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 110, 20));

        jLabeltc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabeltc.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltc.setText(" ");
        jPanel2.add(jLabeltc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 110, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 540, 380));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHỨC NĂNG", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 486, -1));

        jPanel9.setBackground(new java.awt.Color(61, 79, 105));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablept.setRowHeight(20);
        jTablept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableptMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablept);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 590, 490));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 630, 530));

        jPanel5.setBackground(new java.awt.Color(54, 71, 93));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonthoat.setBackground(new java.awt.Color(255, 255, 204));
        jButtonthoat.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Exit.png"))); // NOI18N
        jButtonthoat.setText("THOÁT");
        jButtonthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthoatActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonthoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, 55));

        jButtonxoa.setBackground(new java.awt.Color(255, 255, 204));
        jButtonxoa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Delete.png"))); // NOI18N
        jButtonxoa.setText("XÓA");
        jButtonxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoaActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 97, 55));

        jButtonsua.setBackground(new java.awt.Color(255, 255, 204));
        jButtonsua.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Modify.png"))); // NOI18N
        jButtonsua.setText("SỬA");
        jButtonsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuaActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 96, 55));

        jButtonthem.setBackground(new java.awt.Color(255, 255, 204));
        jButtonthem.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Apply.png"))); // NOI18N
        jButtonthem.setText("THÊM");
        jButtonthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, 55));

        jPanel10.setBackground(new java.awt.Color(61, 79, 105));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 80));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 540, 140));

        jPanel7.setBackground(new java.awt.Color(29, 187, 156));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BẢNG THÔNG TIN PHỤ TÙNG XE");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(388, 388, 388))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 60));

        jPanel4.setBackground(new java.awt.Color(29, 187, 156));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1250, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldtenptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtenptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtenptActionPerformed

    private void jButtonthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemActionPerformed
        // TODO add your handling code here: THÊM PHỤ TÙNG
        try{
        Connect C = new Connect();
        Connection conn = C.getConnection();
        PreparedStatement ps = conn.prepareStatement("insert into dbo.PHUTUNG values(0,?,?,?,?)");
        ps.setString(1, jTextFieldtenpt.getText());
        ps.setString(2, jTextFieldslpt.getText());
        ps.setString(3, jTextFielddongia.getText());
        ps.setString(4, jComboBoxloaitc.getSelectedItem().toString());
        int chk = ps.executeUpdate();
        if (chk  >0){
            jLabeltt.setText("Thêm thành công");
        //    JOptionPane.showMessageDialog(this, "Đã thêm thành công !");
        }        
            Y.setRowCount(0);
            Load();
    }catch(Exception ex){
        ex.getMessage();
        System.out.println(ex.toString());
        JOptionPane.showMessageDialog(this, "Thêm thất bại ! Bạn hãy nhập kỹ thông tin phụ tùng");
        jLabeltt.setText("");
    }
    jTextFieldtenpt.setText("");
    jTextFieldslpt.setText("");
    jTextFielddongia.setText("");
    }//GEN-LAST:event_jButtonthemActionPerformed

    private void jButtonsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuaActionPerformed
        // TODO add your handling code here: SỬA THÔNG SỐ PHỤ TÙNG
        try{
        Connect c = new Connect();
        Connection conn = c.getConnection();
        int index =jTablept.getSelectedRow();
        String value = jTablept.getModel().getValueAt(index,0).toString();   
        PreparedStatement ps = conn.prepareStatement("Update PHUTUNG set TENPT=?, SOLUONGPT=?, DONGIA=?, MATC=? where MAPT='"+value+"'");
        ps.setString(1, jTextFieldtenpt.getText());
        ps.setString(2, jTextFieldslpt.getText());
        ps.setString(3, jTextFielddongia.getText());
        ps.setString(4, jComboBoxloaitc.getSelectedItem().toString());
        int chk = ps.executeUpdate();
        if (chk  >0){
            jLabeltt.setText("Sữa thành công");
        //    JOptionPane.showMessageDialog(this, "Đã sửa thành công !");
        }
        
            Y.setRowCount(0);
            Load();
    }catch(Exception ex){
        System.out.println(ex.toString());
        JOptionPane.showMessageDialog(this, "Sửa thất bại ! Bạn hãy nhập kỹ thông tin");
        jLabeltt.setText("");
    }
    jTextFieldtenpt.setText("");
    jTextFieldslpt.setText("");
    jTextFielddongia.setText("");
    }//GEN-LAST:event_jButtonsuaActionPerformed

    private void jButtonxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoaActionPerformed
        // TODO add your handling code here: XÓA PHỤ TÙNG
        try {
            Connect c = new Connect();
            Connection conn = c.getConnection();
            PreparedStatement ps = conn.prepareStatement("delete dbo.PHUTUNG where MAPT=?");
            ps.setString(1,jTablept.getValueAt(jTablept.getSelectedRow(),0).toString());
            if(JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa không ?","Ðồng Ý",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                jLabeltt.setText("Xóa thành công");
                ps.executeUpdate();
                Y.setRowCount(0);
                Load();
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
            JOptionPane.showMessageDialog(this, "Xóa thất bại !");
            jLabeltt.setText("");
        }
        jTextFieldtenpt.setText("");
        jTextFieldslpt.setText("");
        jTextFielddongia.setText("");
    }//GEN-LAST:event_jButtonxoaActionPerformed

    private void jButtonthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthoatActionPerformed
        // TODO add your handling code here: THOÁT KHỎI THÊM PHỤ TÙNG
        if(JOptionPane.showConfirmDialog(this,"Xác Nhận Thoát ?","Đồng Ý",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) { 
        this.setVisible(false);}
    }//GEN-LAST:event_jButtonthoatActionPerformed

    private void jTextFieldtenptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldtenptMouseClicked
        // TODO add your handling code here:
        jLabeltt.setText("");
    }//GEN-LAST:event_jTextFieldtenptMouseClicked

    private void jTableptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableptMouseClicked
        // TODO add your handling code here:
        jLabeltt.setText("");
    }//GEN-LAST:event_jTableptMouseClicked

    private void jComboBoxloaitcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxloaitcActionPerformed
        // TODO add your handling code here:
        jLabeltentc.setText("");
        jLabeltc.setText("");
        try{
        Connect c = new Connect();
        Connection conn = c.getConnection();
        PreparedStatement p = conn.prepareStatement("select * from TIENCONG");
        ResultSet rs = p.executeQuery();
        while(rs.next())
        {
            if(jComboBoxloaitc.getSelectedItem().toString().equalsIgnoreCase(rs.getString("MATC"))){    
                jLabeltentc.setText(rs.getString("TENTC"));
                jLabeltc.setText(rs.getString("TC"));
            }
        }
            }catch (SQLException ex){
                Logger.getLogger(LAPHOADON.class.getName()).log(Level.SEVERE, null, ex);
            }   
    }//GEN-LAST:event_jComboBoxloaitcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(THEMPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(THEMPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(THEMPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(THEMPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new THEMPT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonsua;
    private javax.swing.JButton jButtonthem;
    private javax.swing.JButton jButtonthoat;
    private javax.swing.JButton jButtonxoa;
    private javax.swing.JComboBox<String> jComboBoxloaitc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeltc;
    private javax.swing.JLabel jLabeltentc;
    private javax.swing.JLabel jLabeltt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablept;
    private javax.swing.JTextField jTextFielddongia;
    private javax.swing.JTextField jTextFieldslpt;
    private javax.swing.JTextField jTextFieldtenpt;
    // End of variables declaration//GEN-END:variables
}
