/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chucnang;

import MenuConnect.Connect;
    import java.awt.Dimension;
    import java.awt.Graphics;
    import java.sql.Connection;
    import java.sql.PreparedStatement;
    import java.sql.ResultSet;
    import java.sql.ResultSetMetaData;
    import java.sql.Statement;
    import java.text.DateFormat;
    import java.text.ParseException;
    import java.text.SimpleDateFormat;
    import java.util.Date;
    import java.util.Vector;
    import java.util.logging.Level;
    import javax.swing.ImageIcon;
    import javax.swing.JOptionPane;
    import javax.swing.event.ListSelectionEvent;
    import javax.swing.event.ListSelectionListener;
    import javax.swing.table.DefaultTableModel;
    import java.util.Scanner;
/**
 *
 * @author Administrator
 */
public class TNXE extends javax.swing.JFrame {
    DefaultTableModel Y = new DefaultTableModel();

    /**
     * Creates new form TNXE
     */
    public TNXE() {
        initComponents();
        Load();
        LoadCBHX();
    }
    public static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
        if(date != null){
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            return sqlDate;
        }
        return null;
    } 
    
    public static java.util.Date convertSqlDateToUtilDate(java.sql.Date date){
        if(date != null){
            java.util.Date sqlDate = new java.util.Date(date.getTime());
            return sqlDate;
        }
        return null;
    }
    public void Load(){
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        try{
            Connect C = new Connect();
            Connection conn = C.getConnection();
            int number;
            Vector row, column = null;
            column = new Vector();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from KHACHHANG");
            ResultSetMetaData metadata = rs.getMetaData();
            number = metadata.getColumnCount();
            for (int i = 1; i <= number;  i++){
                column.add(metadata.getColumnName(i));   
            }
            Y.setColumnIdentifiers(column);
            while(rs.next()){
                row = new Vector();
                for(int i=1;i<=number; i++){
                    row.addElement(rs.getString(i));
                }
                Y.addRow(row);
                jTablett.setModel(Y);
            }
        }catch(Exception ex) {
            System.out.println(ex.toString());
        }
    jTablett.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(jTablett.getSelectedRow()>=0){
                    jTextFieldbs.setText(jTablett.getValueAt(jTablett.getSelectedRow(),0) + "");
                    jTextFieldht.setText(jTablett.getValueAt(jTablett.getSelectedRow(),1) + "");
                    jComboBoxhx.setSelectedItem(jTablett.getValueAt(jTablett.getSelectedRow(),2)+ "");
                    jTextFielddt.setText(jTablett.getValueAt(jTablett.getSelectedRow(),3) + "");
                    jTextFielddc.setText(jTablett.getValueAt(jTablett.getSelectedRow(),4) + "");
                        int select = jTablett.getSelectedRow();
                        java.util.Date datel = null;
                    try {
                      datel = new SimpleDateFormat("yyyy-MM-dd").parse((String) Y.getValueAt(select, 5));
                    } catch (ParseException ex) {
                        java.util.logging.Logger.getLogger(TNXE.class.getName()).log(Level.SEVERE, null, ex);
                    }
                        jDateChoosernn.setDate(datel);
                }
            }
        });
    }
    public void LoadCBHX(){
        try{
            Connect a = new Connect();
            Connection conn = a.getConnection();
            PreparedStatement ps = conn.prepareStatement("select HX from HIEUXE");
            ResultSet rs =ps.executeQuery();
            while(rs.next()){
                jComboBoxhx.addItem(rs.getString("HX"));
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldht = new javax.swing.JTextField();
        jTextFieldbs = new javax.swing.JTextField();
        jTextFielddc = new javax.swing.JTextField();
        jTextFielddt = new javax.swing.JTextField();
        jComboBoxhx = new javax.swing.JComboBox<>();
        jDateChoosernn = new com.toedter.calendar.JDateChooser();
        jButtonthemhx = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablett = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonthemmoi = new javax.swing.JButton();
        jButtonsuatt = new javax.swing.JButton();
        jButtonxoatt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("TIẾP NHẬN THÊM XE MỚI");

        jPanel1.setBackground(new java.awt.Color(45, 61, 78));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(61, 79, 105));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ĐỊA CHỈ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, 35));

        jTextFieldht.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldht.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextFieldht, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 330, 40));

        jTextFieldbs.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldbs.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbsActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 330, 50));

        jTextFielddc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFielddc.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextFielddc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 330, 50));

        jTextFielddt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFielddt.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextFielddt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 330, 50));

        jComboBoxhx.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxhx.setForeground(new java.awt.Color(204, 204, 204));
        jComboBoxhx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxhxActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxhx, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 270, 50));

        jDateChoosernn.setForeground(new java.awt.Color(204, 204, 204));
        jDateChoosernn.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDateChoosernn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 330, 50));

        jButtonthemhx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Application.png"))); // NOI18N
        jButtonthemhx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemhxActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonthemhx, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 50, 50));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Today_48px.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Customer_48px.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 60, 60));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Wheel_48px_3.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Number_Pad_48px_1.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Home_48px.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jPanel3.setBackground(new java.awt.Color(54, 71, 93));
        jPanel3.setForeground(new java.awt.Color(54, 71, 93));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HỌ & TÊN");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 180, 40));

        jPanel5.setBackground(new java.awt.Color(54, 71, 93));
        jPanel5.setForeground(new java.awt.Color(54, 71, 93));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/icons8_Barcode_Scanner_48px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BIỂN SỐ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel10))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 180, 50));

        jPanel6.setBackground(new java.awt.Color(54, 71, 93));
        jPanel6.setForeground(new java.awt.Color(54, 71, 93));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HIỆU XE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(33, 33, 33))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 180, 50));

        jPanel7.setBackground(new java.awt.Color(54, 71, 93));
        jPanel7.setForeground(new java.awt.Color(54, 71, 93));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ĐIỆN THOẠI");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 180, 50));

        jPanel8.setBackground(new java.awt.Color(54, 71, 93));
        jPanel8.setForeground(new java.awt.Color(54, 71, 93));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 180, 50));

        jPanel9.setBackground(new java.awt.Color(54, 71, 93));
        jPanel9.setForeground(new java.awt.Color(54, 71, 93));

        jLabel7.setBackground(new java.awt.Color(54, 71, 93));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NGÀY NHẬN");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(21, 21, 21))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 180, 50));

        jPanel12.setBackground(new java.awt.Color(54, 71, 93));
        jPanel12.setForeground(new java.awt.Color(54, 71, 93));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("THÔNG TIN ");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(237, 237, 237))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 680, 510));

        jPanel10.setBackground(new java.awt.Color(61, 79, 105));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablett.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTablett.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablett.setAlignmentX(0.7F);
        jTablett.setAlignmentY(0.7F);
        jTablett.setRowHeight(25);
        jTablett.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablettMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablett);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 656, 570));

        jPanel11.setBackground(new java.awt.Color(54, 71, 93));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("BẢNG THÔNG TIN ĐÃ TIẾP NHẬN");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(94, 94, 94))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 57));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 680, 670));

        jPanel13.setBackground(new java.awt.Color(61, 79, 105));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(54, 71, 93));

        jButtonthemmoi.setBackground(java.awt.SystemColor.scrollbar);
        jButtonthemmoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonthemmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Apply.png"))); // NOI18N
        jButtonthemmoi.setText("Thêm");
        jButtonthemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemmoiActionPerformed(evt);
            }
        });

        jButtonsuatt.setBackground(new java.awt.Color(255, 255, 255));
        jButtonsuatt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonsuatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Modify.png"))); // NOI18N
        jButtonsuatt.setText("Sửa");
        jButtonsuatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuattActionPerformed(evt);
            }
        });

        jButtonxoatt.setBackground(new java.awt.Color(255, 255, 255));
        jButtonxoatt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonxoatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Delete.png"))); // NOI18N
        jButtonxoatt.setText("Xóa");
        jButtonxoatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoattActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/Application.png"))); // NOI18N
        jButton1.setText("LẬP PHIẾU SC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("DỌN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonthemmoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonsuatt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonxoatt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonthemmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonsuatt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonxoatt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 660, 80));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 680, 140));

        jPanel14.setBackground(new java.awt.Color(29, 187, 156));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 820, 1440, 40));

        jPanel15.setBackground(new java.awt.Color(29, 187, 156));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" THÔNG TIN TIẾP NHẬN XE");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(581, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(486, 486, 486))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonthemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemmoiActionPerformed
        // TODO add your handling code here: THÊM KHÁCH HÀNG MỚI
        try{
        Connect C = new Connect();
        Connection conn = C.getConnection();
        PreparedStatement ps = conn.prepareStatement("insert into dbo.KHACHHANG values(?,?,?,?,?,?)");
        ps.setString(1, jTextFieldbs.getText());
        ps.setString(2, jTextFieldht.getText());
        ps.setString(3, jComboBoxhx.getSelectedItem().toString());
        ps.setString(4, jTextFielddt.getText());
        ps.setString(5, jTextFielddc.getText());
        ps.setDate(6, convertUtilDateToSqlDate(jDateChoosernn.getDate()));
        int chk = ps.executeUpdate();
        if (chk  >0){
            JOptionPane.showMessageDialog(this, "Đã thêm thành công !");
        }
            Y.setRowCount(0);
            Load();
    }catch(Exception ex){
        ex.getMessage();
        System.out.println(ex.toString());
        JOptionPane.showMessageDialog(this, "Thêm thất bại ! Bạn hãy nhập kỹ thông tin khách hàng");
    }
    jTextFieldbs.setText("");
    jTextFieldht.setText("");
    jTextFielddc.setText("");
    jTextFielddt.setText("");  
    }//GEN-LAST:event_jButtonthemmoiActionPerformed

    private void jButtonsuattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuattActionPerformed
        // TODO add your handling code here: SỬA THÔNG TIN
        try{
        Connect c = new Connect();
        Connection conn = c.getConnection();
        int index =jTablett.getSelectedRow();
        String value = jTablett.getModel().getValueAt(index,0).toString();   
        PreparedStatement ps = conn.prepareStatement("Update KHACHHANG set TENKH=?, HX=?, DT=?, DC=?, NGAYNHAN=? where BSX='"+value+"'");
        ps.setString(1, jTextFieldht.getText());
        ps.setString(2, jComboBoxhx.getSelectedItem().toString());
        ps.setString(3, jTextFielddt.getText());
        ps.setString(4, jTextFielddc.getText());
        ps.setDate(5, convertUtilDateToSqlDate(jDateChoosernn.getDate()));
        int chk = ps.executeUpdate();
        if (chk  >0){
            JOptionPane.showMessageDialog(this, "Đã sửa thành công !");
        }
        
            Y.setRowCount(0);
            Load();
    }catch(Exception ex){
        System.out.println(ex.toString());
        JOptionPane.showMessageDialog(this, "Sửa thất bại ! Bạn hay sửa lại thông tin chính xác hơn");
    }
        jTextFieldbs.setText("");
        jTextFieldht.setText("");
        jTextFielddt.setText("");
        jTextFielddc.setText("");
    }//GEN-LAST:event_jButtonsuattActionPerformed

    private void jButtonxoattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoattActionPerformed
        // TODO add your handling code here:
        try {
            Connect c = new Connect();
            Connection conn = c.getConnection();
            PreparedStatement ps = conn.prepareStatement("delete dbo.KHACHHANG where BSX=?");
            ps.setString(1,jTablett.getValueAt(jTablett.getSelectedRow(),0).toString());
            if(JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa không ?","Ðồng Ý",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                ps.executeUpdate();
                Y.setRowCount(0);
                Load();
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
            JOptionPane.showMessageDialog(this, "Xóa thất bại ! Hãy thử lại");
        }
        jTextFieldbs.setText("");
        jTextFieldht.setText("");
        jTextFielddt.setText("");
        jTextFielddc.setText("");
    }//GEN-LAST:event_jButtonxoattActionPerformed

    private void jButtonthemhxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemhxActionPerformed
        // TODO add your handling code here: chuyển sang thêm hiệu xe
        THEMHX n = new THEMHX();
        n.setVisible(true);
    }//GEN-LAST:event_jButtonthemhxActionPerformed

    private void jTextFieldbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbsActionPerformed
        // TODO add your handling code here:
        //CODE ĐỊNH FORM BIỂN SỐ
        //
        //
        //
        //
        //
        //
    }//GEN-LAST:event_jTextFieldbsActionPerformed

    private void jComboBoxhxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxhxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxhxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:  CHUYỂN SANG LẬP PHIẾU SỬA CHỬA
        if(JOptionPane.showConfirmDialog(this,"Bạn có muốn lập phiếu sửa chửa không ?","Đồng Ý",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        { 
        this.setVisible(false);
        LAPPS n = new LAPPS();
        n.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTablettMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablettMouseClicked
        // TODO add your handling code here:
        jTextFieldbs.setEditable(false);
    }//GEN-LAST:event_jTablettMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextFieldht.setText("");
        jTextFieldbs.setText("");
        jTextFielddt.setText("");
        jTextFielddc.setText("");
        jTextFieldbs.setEditable(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TNXE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TNXE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TNXE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TNXE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TNXE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonsuatt;
    private javax.swing.JButton jButtonthemhx;
    private javax.swing.JButton jButtonthemmoi;
    private javax.swing.JButton jButtonxoatt;
    private javax.swing.JComboBox<String> jComboBoxhx;
    private com.toedter.calendar.JDateChooser jDateChoosernn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablett;
    private javax.swing.JTextField jTextFieldbs;
    private javax.swing.JTextField jTextFielddc;
    private javax.swing.JTextField jTextFielddt;
    private javax.swing.JTextField jTextFieldht;
    // End of variables declaration//GEN-END:variables
}
